//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.WindowsForms.QueueReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueueReference.IWcfQueueRequest")]
    public interface IWcfQueueRequest {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfQueueRequest/SendCustomersRequest")]
        void SendCustomersRequest();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfQueueRequest/SendCustomersRequest")]
        System.Threading.Tasks.Task SendCustomersRequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfQueueRequest/SendGoodsRequest")]
        void SendGoodsRequest();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfQueueRequest/SendGoodsRequest")]
        System.Threading.Tasks.Task SendGoodsRequestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfQueueRequestChannel : WCF.WindowsForms.QueueReference.IWcfQueueRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfQueueRequestClient : System.ServiceModel.ClientBase<WCF.WindowsForms.QueueReference.IWcfQueueRequest>, WCF.WindowsForms.QueueReference.IWcfQueueRequest {
        
        public WcfQueueRequestClient() {
        }
        
        public WcfQueueRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfQueueRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfQueueRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfQueueRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendCustomersRequest() {
            base.Channel.SendCustomersRequest();
        }
        
        public System.Threading.Tasks.Task SendCustomersRequestAsync() {
            return base.Channel.SendCustomersRequestAsync();
        }
        
        public void SendGoodsRequest() {
            base.Channel.SendGoodsRequest();
        }
        
        public System.Threading.Tasks.Task SendGoodsRequestAsync() {
            return base.Channel.SendGoodsRequestAsync();
        }
    }
}
